// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chamgyqlolnobhyqnrng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoYW1neXFsb2xub2JoeXFucm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODM4MjUsImV4cCI6MjA2OTc1OTgyNX0.JhTNYOhG8F20JoIh2nwQSaGpdR_19u8Kkv046vILtSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});